---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "3970E4"
- name: area/github
  color: "000000"
- name: area/go
  color: "844FBA"

# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/go
  color: "844FBA"
- name: renovate/container
  color: "3970E4"
- name: renovate/github-action
  color: "000000"

# =================================================================================================
# Semantic Types
# =================================================================================================
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
