---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Delete Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to delete"
        required: true
        default: "latest"
      dry-run:
        type: number
        description: "Dry run"
        required: true
        default: 1

jobs:
  delete:
    uses: mirceanton/reusable-workflows/.github/workflows/docker-delete.yaml@main
    secrets: inherit
    with:
      image-name: ${{ github.event.repository.name }}
      image-tag: ${{ github.event.inputs.tag }}
      dry-run: ${{ github.event.inputs.dry-run }}
