---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    with:
      golangci-version: v1.64.3

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
